version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: "your_surname"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_DB: "PostgreSQL_Sokolov"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - my_network

  python:
    image: python:3.9
    container_name: python_app
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install psycopg2 && python3 app.py"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
